version: "3"

services:
  postgres:
    image: postgres:16.0-alpine3.18
    container_name: pg
    env_file:
    - ./.env
    ports:
      - "5432:5432"
    volumes:
      - /Users/gabriel/Desktop/imobapp-volume:/var/lib/postgresql/data

