version: "3"

services:
  postgres:
    image: postgres:16.0
    container_name: pg
    env_file:
    - ./.env
    ports:
      - "5432:5432"
    volumes:
      - /Users/gabriel/Desktop/apps/imobapp/volumes
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"