version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: pg
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: imobappdev
    ports:
      - "5432:5432"
