# fly.toml app configuration file generated for imobapp on 2023-11-15T08:37:57-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "imobapp"
primary_region = "gig"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
