# fly.toml app configuration file generated for imobapp on 2023-11-14T15:54:23-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "imobapp"
primary_region = "gig"

[build]

[env]
  CACHE_DRIVER = "redis"
  REDIS_CACHE_DN = "0"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
