export class GranatumCostumersSupliersMock {
  allItems = costumersSupliersMocks;

  async getAll() {
    return this.allItems;
  }
}

export const costumersSupliersMocks = [
  {
    id: 2495918,
    nome: 'Bernadate',
    nome_fantasia: 'Loja da Bernadete',
    documento: '12345678900',
    inscricao_estadual: '987654',
    inscricao_municipal: '12345',
    telefone: '(00) 0000-0000',
    endereco: 'Rua da Amizade',
    endereco_numero: '123',
    endereco_complemento: 'Sala 2A',
    bairro: 'Centro',
    cep: '12345-678',
    cidade_id: 123,
    estado_id: 45,
    email: 'bernadete@email.com',
    observacao: 'Cliente fiel',
    banco_id: 567,
    agencia: '0123',
    numero_conta: '4567890-1',
    ativo: true,
    fornecedor: true,
    cliente: true,
    classificacao_cliente_id: 1,
    classificacao_fornecedor_id: 2,
    estado: 'São Paulo',
    cidade: 'São José dos Campos',
    anexos: [],
  },
  {
    id: 2495919,
    nome: 'Lucas Silva',
    nome_fantasia: 'Lucas Auto Peças',
    documento: '98765432100',
    inscricao_estadual: '654321',
    inscricao_municipal: '54321',
    telefone: '(00) 0000-0000',
    endereco: 'Avenida das Peças',
    endereco_numero: '789',
    endereco_complemento: 'Loja 5',
    bairro: 'Industrial',
    cep: '54321-987',
    cidade_id: 456,
    estado_id: 78,
    email: 'lucas@email.com',
    observacao: 'Ótimo fornecedor',
    banco_id: 901,
    agencia: '4567',
    numero_conta: '1234567-8',
    ativo: true,
    fornecedor: true,
    cliente: false,
    classificacao_cliente_id: 0,
    classificacao_fornecedor_id: 3,
    estado: 'Rio de Janeiro',
    cidade: 'Rio de Janeiro',
    anexos: [],
  },
  {
    id: 2495920,
    nome: 'Fernanda Pereira',
    nome_fantasia: 'Fernanda Modas',
    documento: '13579246800',
    inscricao_estadual: '246810',
    inscricao_municipal: '98765',
    telefone: '(00) 0000-0000',
    endereco: 'Rua das Tendências',
    endereco_numero: '567',
    endereco_complemento: 'Sala 3B',
    bairro: 'Fashion',
    cep: '12345-543',
    cidade_id: 789,
    estado_id: 12,
    email: 'fernanda@email.com',
    observacao: 'Cliente frequente',
    banco_id: 234,
    agencia: '9876',
    numero_conta: '5432109-8',
    ativo: true,
    fornecedor: false,
    cliente: true,
    classificacao_cliente_id: 2,
    classificacao_fornecedor_id: 0,
    estado: 'São Paulo',
    cidade: 'São Paulo',
    anexos: [],
  },
  {
    id: 2495921,
    nome: 'João Carlos',
    nome_fantasia: 'João Lanches',
    documento: '98712345600',
    inscricao_estadual: '1234567',
    inscricao_municipal: '76543',
    telefone: '(00) 0000-0000',
    endereco: 'Avenida dos Lanches',
    endereco_numero: '543',
    endereco_complemento: 'Loja 1',
    bairro: 'Centro',
    cep: '54321-123',
    cidade_id: 654,
    estado_id: 32,
    email: 'joao@email.com',
    observacao: 'Melhor lanche da cidade',
    banco_id: 876,
    agencia: '5432',
    numero_conta: '1234567-0',
    ativo: true,
    fornecedor: true,
    cliente: true,
    classificacao_cliente_id: 1,
    classificacao_fornecedor_id: 2,
    estado: 'Minas Gerais',
    cidade: 'Belo Horizonte',
    anexos: [],
  },
  {
    id: 2495922,
    nome: 'The Companny',
    nome_fantasia: 'Doces da Maria',
    documento: '24681012000100',
    inscricao_estadual: '9876543',
    inscricao_municipal: '123456',
    telefone: '(00) 0000-0000',
    endereco: 'Rua dos Doces',
    endereco_numero: '987',
    endereco_complemento: 'Casa 2',
    bairro: 'Doçura',
    cep: '98765-432',
    cidade_id: 123,
    estado_id: 41,
    email: 'maria@email.com',
    observacao: 'Doces artesanais de qualidade',
    banco_id: 321,
    agencia: '1234',
    numero_conta: '8765432-1',
    ativo: true,
    fornecedor: false,
    cliente: true,
    classificacao_cliente_id: 2,
    classificacao_fornecedor_id: 0,
    estado: 'Paraná',
    cidade: 'Curitiba',
    anexos: [],
  },
];
