import { ImobziPropertyDetailsDTO } from 'src/3party-client/imobzi/imobzi-properties/dtos/imobziPropertyDetails.dtos';

export class ImobziPropertiesMock {
  pagination = {
    unavailableProperties: {
      page1: { count: 1, cursor: 'abc', properties: [{ status: 'rented', db_id: 1 }] },
      page2: { count: 1, cursor: null, properties: [{ status: 'rented', db_id: 2 }] },
    },
    availableProperties: {
      page1: { count: 1, cursor: 'def', properties: [{ status: 'available', db_id: 1234567890 }] },
      page2: { count: 1, cursor: null, properties: [{ status: 'available', db_id: 2 }] },
    },
  };
  allPropertiesFullData: ImobziPropertyDetailsDTO[] = [
    {
      code: '32',
      neighborhood: 'Universitário',
      features: {},
      links: [],
      multimidias: [],
      elevators: 0,
      sun_position: 'south face',
      has_lease_linked: true,
      alternative_code: '72',
      site_highlights_section: null,
      updated_at: '2023-09-04T18:27:08.179632Z',
      zipcode: '55016-400',
      buildings: 0,
      vacation_rental: false,
      bedroom: 2,
      lot_measure_behind: 0.0,
      property_type: 'apartament',
      stage: 'ready',
      building_name: 'Eko Home Club',
      city: 'São Paulo',
      bathroom: 2,
      photos_count: 0,
      network: null,
      area: 60.0,
      lot_area: 0.0,
      property_dimension: '',
      visit_only_realtor: false,
      site_url: 'www.site/eko-home-club--ipe-',
      state: 'SP',
      property_block: 'Ipê',
      site_title: 'Apartamento em Universitário  -  Caruaru',
      lot_measure_left: 0.0,
      latitude: -8.265177399999999,
      suite: 1,
      proposal: null,
      lot_measure_radius: 0.0,
      rental_value: 1000.0,
      member_register_code: null,
      unit_floor: 0,
      status: 'rented',
      lot_measure_front: 0.0,
      url_share: 'www.site.to.share.com',
      db_id: 1111111111111,
      useful_area: 60.0,
      description: '',
      visit_time: '',
      cover_photo: {
        url: '',
        db_id: 0,
      },
      property_calendar: [],
      lot_measure_right: 0.0,
      photos: {},
      built: 0,
      property_unity: 2202,
      finality: 'residential',
      address: 'Great Palace, 324',
      active: true,
      site_highlights_position: 0,
      cover_photo_private: {
        url: '',
        db_id: 0,
      },
      building: false,
      building_id: 99999999999,
      owners: [
        {
          code: '1',
          name: 'Jan Inc',
          id: 2222222222,
          rate: null,
          percentage: 50.0,
          type: 'organization',
        },
        {
          code: '2',
          name: 'Mary Doe',
          id: 44444444,
          rate: null,
          percentage: 50.0,
          type: 'person',
        },
      ],
      measure_type: 'M²',
      address_complement: 'Bloco Ipê - Apto. 2202',
      new_code: '32',
      database: 'ac-tbms22919lykc',
      has_contract_linked: true,
      created_at: '2022-10-12T16:10:05.545984Z',
      lot_measure_type: '',
      property_situation: 'with_deed',
      sale_value: 330000.0,
      longitude: -35.96419040000001,
      units_per_floor: 0,
      garage: 2,
      site_description: '',
      floors: 0,
      building_code: '2',
      country: 'Brasil',
      available_digital_real_estate: false,
      site_publish: false,
      site_publish_price: false,
      send_owner_property_review: false,
      site_meta_description: '',
      key_id: '',
    },
  ];
  async getPropertyFullData(idProperty: string): Promise<ImobziPropertyDetailsDTO> {
    return this.allPropertiesFullData.find((property) => property.db_id.toString() === idProperty);
  }
}
