import { Invoice } from 'src/modules/invoices/entities/invoice.entity';
import { inMemoryLeasesRepositoryMock } from '../inMemoryLeasesRepository/inMemoryLeasesRepository.mock';

export const inMemoryInvoicesRepositoryMock: Invoice[] = [
  {
    id_imobzi: 'id_imobzi_1',
    status: 'status',
    due_date: new Date('2022-01-01T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[6].id_imobzi,
    management_fee: 1,
    invoice_url: 'invoice_url_1',
    total_value: 100,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_2',
    status: 'status',
    due_date: new Date('2022-01-02T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[6].id_imobzi,
    management_fee: 2,
    invoice_url: 'invoice_url_2',
    total_value: 200,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_3',
    status: 'status',
    due_date: new Date('2022-01-03T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[6].id_imobzi,
    management_fee: 3,
    invoice_url: 'invoice_url_3',
    total_value: 300,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_4',
    status: 'status',
    due_date: new Date('2022-01-04T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[6].id_imobzi,
    management_fee: 4,
    invoice_url: 'invoice_url_4',
    total_value: 400,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_5',
    status: 'status',
    due_date: new Date('2022-01-05T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[6].id_imobzi,
    management_fee: 5,
    invoice_url: 'invoice_url_5',
    total_value: 500,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_6',
    status: 'status',
    due_date: new Date('2022-01-06T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[4].id_imobzi,
    management_fee: 6,
    invoice_url: 'invoice_url_6',
    total_value: 600,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_7',
    status: 'status',
    due_date: new Date('2022-01-07T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[4].id_imobzi,
    management_fee: 7,
    invoice_url: 'invoice_url_7',
    total_value: 700,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_8',
    status: 'status',
    due_date: new Date('2022-01-08T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[4].id_imobzi,
    management_fee: 8,
    invoice_url: 'invoice_url_8',
    total_value: 800,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_9',
    status: 'status',
    due_date: new Date('2022-01-09T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[4].id_imobzi,
    management_fee: 9,
    invoice_url: 'invoice_url_9',
    total_value: 900,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_10',
    status: 'status',
    due_date: new Date('2022-01-10T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 10,
    invoice_url: 'invoice_url_10',
    total_value: 1000,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_11',
    status: 'status',
    due_date: new Date('2022-01-11T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 11,
    invoice_url: 'invoice_url_11',
    total_value: 1100,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_12',
    status: 'status',
    due_date: new Date('2022-01-12T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 12,
    invoice_url: 'invoice_url_12',
    total_value: 1200,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_13',
    status: 'status',
    due_date: new Date('2022-01-13T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 13,
    invoice_url: 'invoice_url_13',
    total_value: 1300,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_14',
    status: 'status',
    due_date: new Date('2022-01-14T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 14,
    invoice_url: 'invoice_url_14',
    total_value: 1400,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_15',
    status: 'status',
    due_date: new Date('2022-01-15T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[4].id_imobzi,
    management_fee: 15,
    invoice_url: 'invoice_url_15',
    total_value: 1500,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_16',
    status: 'status',
    due_date: new Date('2022-01-16T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[4].id_imobzi,
    management_fee: 16,
    invoice_url: 'invoice_url_16',
    total_value: 1600,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_17',
    status: 'status',
    due_date: new Date('2022-01-17T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[4].id_imobzi,
    management_fee: 17,
    invoice_url: 'invoice_url_17',
    total_value: 1700,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_18',
    status: 'status',
    due_date: new Date('2022-01-18T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[4].id_imobzi,
    management_fee: 18,
    invoice_url: 'invoice_url_18',
    total_value: 1800,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_19',
    status: 'status',
    due_date: new Date('2022-01-19T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 19,
    invoice_url: 'invoice_url_19',
    total_value: 1900,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_20',
    status: 'status',
    due_date: new Date('2022-01-20T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[3].id_imobzi,
    management_fee: 20,
    invoice_url: 'invoice_url_20',
    total_value: 2000,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_21',
    status: 'status',
    due_date: new Date('2022-01-21T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[3].id_imobzi,
    management_fee: 21,
    invoice_url: 'invoice_url_21',
    total_value: 2100,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_22',
    status: 'status',
    due_date: new Date('2022-01-22T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[3].id_imobzi,
    management_fee: 22,
    invoice_url: 'invoice_url_22',
    total_value: 2200,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_23',
    status: 'status',
    due_date: new Date('2022-01-23T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[3].id_imobzi,
    management_fee: 23,
    invoice_url: 'invoice_url_23',
    total_value: 2300,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_24',
    status: 'status',
    due_date: new Date('2022-01-24T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[3].id_imobzi,
    management_fee: 24,
    invoice_url: 'invoice_url_24',
    total_value: 2400,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_25',
    status: 'status',
    due_date: new Date('2022-01-25T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[1].id_imobzi,
    management_fee: 25,
    invoice_url: 'invoice_url_25',
    total_value: 2500,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_26',
    status: 'status',
    due_date: new Date('2022-01-26T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[1].id_imobzi,
    management_fee: 26,
    invoice_url: 'invoice_url_26',
    total_value: 2600,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_27',
    status: 'status',
    due_date: new Date('2022-01-27T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[1].id_imobzi,
    management_fee: 27,
    invoice_url: 'invoice_url_27',
    total_value: 2700,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_28',
    status: 'status',
    due_date: new Date('2022-01-28T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[1].id_imobzi,
    management_fee: 28,
    invoice_url: 'invoice_url_28',
    total_value: 2800,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_29',
    status: 'status',
    due_date: new Date('2022-01-29T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[1].id_imobzi,
    management_fee: 29,
    invoice_url: 'invoice_url_29',
    total_value: 2900,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_30',
    status: 'status',
    due_date: new Date('2022-01-30T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 30,
    invoice_url: 'invoice_url_30',
    total_value: 3000,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_31',
    status: 'status',
    due_date: new Date('2022-01-31T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[4].id_imobzi,
    management_fee: 31,
    invoice_url: 'invoice_url_31',
    total_value: 3100,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_32',
    status: 'status',
    due_date: new Date('2022-02-01T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[4].id_imobzi,
    management_fee: 32,
    invoice_url: 'invoice_url_32',
    total_value: 3200,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_33',
    status: 'status',
    due_date: new Date('2022-02-02T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[4].id_imobzi,
    management_fee: 33,
    invoice_url: 'invoice_url_33',
    total_value: 3300,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_34',
    status: 'status',
    due_date: new Date('2022-02-03T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[4].id_imobzi,
    management_fee: 34,
    invoice_url: 'invoice_url_34',
    total_value: 3400,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_35',
    status: 'status',
    due_date: new Date('2022-02-04T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 35,
    invoice_url: 'invoice_url_35',
    total_value: 3500,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_36',
    status: 'status',
    due_date: new Date('2022-02-05T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 36,
    invoice_url: 'invoice_url_36',
    total_value: 3600,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_37',
    status: 'status',
    due_date: new Date('2022-02-06T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 37,
    invoice_url: 'invoice_url_37',
    total_value: 3700,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_38',
    status: 'status',
    due_date: new Date('2022-02-07T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 38,
    invoice_url: 'invoice_url_38',
    total_value: 3800,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_39',
    status: 'status',
    due_date: new Date('2022-02-08T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 39,
    invoice_url: 'invoice_url_39',
    total_value: 3900,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_40',
    status: 'status',
    due_date: new Date('2022-02-09T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 40,
    invoice_url: 'invoice_url_40',
    total_value: 4000,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_41',
    status: 'status',
    due_date: new Date('2022-02-10T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 41,
    invoice_url: 'invoice_url_41',
    total_value: 4100,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_42',
    status: 'status',
    due_date: new Date('2022-02-11T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 42,
    invoice_url: 'invoice_url_42',
    total_value: 4200,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_43',
    status: 'status',
    due_date: new Date('2022-02-12T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 43,
    invoice_url: 'invoice_url_43',
    total_value: 4300,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_44',
    status: 'status',
    due_date: new Date('2022-02-13T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 44,
    invoice_url: 'invoice_url_44',
    total_value: 4400,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_45',
    status: 'status',
    due_date: new Date('2022-02-14T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 45,
    invoice_url: 'invoice_url_45',
    total_value: 4500,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_46',
    status: 'status',
    due_date: new Date('2022-02-15T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 46,
    invoice_url: 'invoice_url_46',
    total_value: 4600,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_47',
    status: 'status',
    due_date: new Date('2022-02-16T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 47,
    invoice_url: 'invoice_url_47',
    total_value: 4700,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_48',
    status: 'status',
    due_date: new Date('2022-02-17T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 48,
    invoice_url: 'invoice_url_48',
    total_value: 4800,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_49',
    status: 'status',
    due_date: new Date('2022-02-18T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 49,
    invoice_url: 'invoice_url_49',
    total_value: 4900,
    invoiceItems: [],
  },
  {
    id_imobzi: 'id_imobzi_50',
    status: 'status',
    due_date: new Date('2022-02-19T00:00:00.000Z'),
    id_lease_imobzi: inMemoryLeasesRepositoryMock[5].id_imobzi,
    management_fee: 50,
    invoice_url: 'invoice_url_50',
    total_value: 5000,
    invoiceItems: [],
  },
];
