export const getLeaseFullDataFromImobziMock = {
  updated_at: '2023-01-01T00:00:00.000Z',
  duration: 30,
  start_at: '2023-01-01',
  indeterminate: true,
  irrf: true,
  include_in_dimob: true,
  status: 'active',
  code: '44',
  db_id: 11111111,
  annual_readjustment: { db_id: '999999999', name: 'IPCA' }, // here, imobzi's api returns db_id as string
  property: { db_id: 3333333 },
  guarantee: { guarantee_type: 'guarantor', details: { value: 3000 }, sponsor: { db_id: 4444444 } },
  tenants: [{ db_id: 555555, type: 'person' }],
  management_fee: { percent: 15 },
  items: [
    {
      landlords: [],
      due_date: '2023-08-27',
      repeat_total: 11,
      description: 'Seguro Incêndio',
      bar_code: '',
      charge_management_fee: false,
      recurrent: true,
      value: 11.63,
      item_type: null,
      until_due_date: false,
      behavior: 'charge_tenant',
      autopay_on_due_date: false,
      repeat_index: 2,
      include_in_dimob: false,
      contact_key: null,
      start_date: '',
    },
    {
      landlords: [],
      due_date: '2023-08-27',
      repeat_total: 10,
      description: 'IPTU',
      bar_code: '',
      charge_management_fee: false,
      recurrent: true,
      value: 85.69,
      item_type: null,
      until_due_date: false,
      behavior: 'charge_tenant_and_onlend',
      autopay_on_due_date: false,
      repeat_index: 9,
      include_in_dimob: false,
      contact_key: null,
      start_date: '',
    },
  ],
  beneficiaries: [
    {
      code: '4',
      pix: [
        {
          default: true,
          pix_key_type: 'cpf_cnpj',
          pix_key: '001.001.001-00',
        },
      ],

      cpf: '001.001.001-00',
      percent: 50.0,
      type: 'person',
      db_id: 11111111111,
    },
    {
      code: '5',
      pix: [
        {
          default: true,
          pix_key_type: 'cpf_cnpj',
          pix_key: '001.867.244-20',
        },
      ],

      cpf: '002.002.002-00',
      percent: 50.0,
      type: 'organization',
      db_id: 22222222222,
    },
  ],
};

export const filterLeasesMainDataToDbMock = {
  beneficiaries: [
    {
      id_lease_imobzi: '11111111',
      id_beneficiary_organization: null,
      id_beneficiary_person: '11111111111',
      share: 50,
    },
    {
      id_lease_imobzi: '11111111',
      id_beneficiary_organization: '22222222222',
      id_beneficiary_person: null,
      share: 50,
    },
  ],
  updated_at: new Date('2023-01-01T00:00:00.000Z'),
  id_annual_readjustment_imobzi: '999999999',
  code_imobzi: '44',
  duration: 30,
  fee: 15,
  guarantee_type: 'guarantor',
  guarantee_value: 3000,
  id_imobzi: '11111111',
  id_tenant_organization_imobzi: null,
  id_main_guarantor_imobzi: '4444444',
  id_tenant_person_imobzi: '555555',
  include_in_dimob: true,
  indeterminate: true,
  irrf: true,
  lease_value: undefined,
  id_property_imobzi: '3333333',
  start_at: '2023-01-01',
  status: 'active',
  leaseItems: [
    {
      due_date: '2023-08-27',
      repeat_total: 11,
      description: 'Seguro Incêndio',
      charge_management_fee: false,
      recurrent: true,
      value: 11.63,
      until_due_date: false,
      behavior: 'charge_tenant',
      repeat_index: 2,
      include_in_dimob: false,
      start_date: '',
    },
    {
      due_date: '2023-08-27',
      repeat_total: 10,
      description: 'IPTU',
      charge_management_fee: false,
      recurrent: true,
      value: 85.69,
      until_due_date: false,
      behavior: 'charge_tenant_and_onlend',
      repeat_index: 9,
      include_in_dimob: false,
      start_date: '',
    },
  ],
};
