import { CreateLeaseDTO } from 'src/repository/leases/dtos/create-lease.dtos';
import { inMemoryOrganizationsRepositoryMock } from '../inMemoryOrganizationsRepository/inMemoryOrganizationsRepository.mock';
import { inMemoryPeopleRepositoryMock } from '../inMemoryPeopleRepository/inMemoryPeopleRepository.mocks';
import { inMemoryPropertiesRepositoryMock } from '../inMemoryPropertiesRepository/inMemoryPropertiesRepository.mock';

export const inMemoryLeasesRepositoryMock: CreateLeaseDTO[] = [
  {
    id: 1,
    id_imobzi: 'ABC123',
    status: 'Active',
    code_imobzi: 'XYZ789',
    start_at: new Date('2023-01-15'),
    duration: 12,
    id_property_imobzi: inMemoryPropertiesRepositoryMock[6].id_imobzi,
    id_tenant_person_imobzi: inMemoryPeopleRepositoryMock[0].id_imobzi,
    id_tenant_organization_imobzi: null,
    id_main_guarantor_imobzi: inMemoryPeopleRepositoryMock[3].id_imobzi,
    fee: 1000,
    guarantee_type: 'Security Deposit',
    guarantee_value: 2000,
    id_annual_readjustment_imobzi: 'ADJUSTMENT1',
    irrf: true,
    include_in_dimob: true,
    indeterminate: false,
    lease_value: 1500,
    beneficiaries: [],
    lease_items: [],
  },
  {
    id: 2,
    id_imobzi: 'DEF456',
    status: 'Active',
    code_imobzi: 'PQR123',
    start_at: new Date('2023-02-20'),
    duration: 6,
    id_property_imobzi: inMemoryPropertiesRepositoryMock[2].id_imobzi,
    id_tenant_person_imobzi: null,
    id_tenant_organization_imobzi: inMemoryOrganizationsRepositoryMock[3].id_imobzi,
    id_main_guarantor_imobzi: null,
    fee: 1200,
    guarantee_type: 'Bank Guarantee',
    guarantee_value: 2500,
    id_annual_readjustment_imobzi: 'ADJUSTMENT2',
    irrf: false,
    include_in_dimob: true,
    indeterminate: true,
    lease_value: 1800,
    beneficiaries: [],
    lease_items: [],
  },
  {
    id: 3,
    id_imobzi: 'GHI789',
    status: 'Inactive',
    code_imobzi: 'LMN456',
    start_at: new Date('2023-03-10'),
    duration: 24,
    id_property_imobzi: inMemoryPropertiesRepositoryMock[0].id_imobzi,
    id_tenant_person_imobzi: inMemoryPeopleRepositoryMock[5].id_imobzi,
    id_tenant_organization_imobzi: null,
    id_main_guarantor_imobzi: null,
    fee: 800,
    guarantee_type: 'Cash Deposit',
    guarantee_value: 1500,
    id_annual_readjustment_imobzi: 'ADJUSTMENT3',
    irrf: true,
    include_in_dimob: false,
    indeterminate: false,
    lease_value: 1000,
    beneficiaries: [],
    lease_items: [],
  },
  {
    id: 4,
    id_imobzi: 'JKL012',
    status: 'Active',
    code_imobzi: 'STU789',
    start_at: new Date('2023-04-05'),
    duration: 36,
    id_property_imobzi: inMemoryPropertiesRepositoryMock[5].id_imobzi,
    id_tenant_person_imobzi: inMemoryPeopleRepositoryMock[3].id_imobzi,
    id_tenant_organization_imobzi: null,
    id_main_guarantor_imobzi: inMemoryPeopleRepositoryMock[2].id_imobzi,
    fee: 1500,
    guarantee_type: 'Bank Guarantee',
    guarantee_value: 3000,
    id_annual_readjustment_imobzi: 'ADJUSTMENT4',
    irrf: false,
    include_in_dimob: true,
    indeterminate: true,
    lease_value: 2200,
    beneficiaries: [],
    lease_items: [],
  },
  {
    id: 5,
    id_imobzi: 'MNO345',
    status: 'Active',
    code_imobzi: 'VWX123',
    start_at: new Date('2023-05-15'),
    duration: 12,
    id_property_imobzi: inMemoryPropertiesRepositoryMock[0].id_imobzi,
    id_tenant_person_imobzi: inMemoryPeopleRepositoryMock[0].id_imobzi,
    id_tenant_organization_imobzi: null,
    id_main_guarantor_imobzi: inMemoryPeopleRepositoryMock[5].id_imobzi,
    fee: 900,
    guarantee_type: 'Security Deposit',
    guarantee_value: 1800,
    id_annual_readjustment_imobzi: 'ADJUSTMENT5',
    irrf: true,
    include_in_dimob: true,
    indeterminate: false,
    lease_value: 1300,
    beneficiaries: [],
    lease_items: [],
  },
  {
    id: 6,
    id_imobzi: 'PQR678',
    status: 'Inactive',
    code_imobzi: 'YZA456',
    start_at: new Date('2023-06-20'),
    duration: 6,
    id_property_imobzi: inMemoryPropertiesRepositoryMock[0].id_imobzi,
    id_tenant_person_imobzi: inMemoryPeopleRepositoryMock[0].id_imobzi,
    id_tenant_organization_imobzi: null,
    id_main_guarantor_imobzi: inMemoryPeopleRepositoryMock[1].id_imobzi,
    fee: 1100,
    guarantee_type: 'Cash Deposit',
    guarantee_value: 2200,
    id_annual_readjustment_imobzi: 'ADJUSTMENT6',
    irrf: false,
    include_in_dimob: true,
    indeterminate: true,
    lease_value: 1600,
    beneficiaries: [],
    lease_items: [],
  },
  {
    id: 7,
    id_imobzi: 'STU901',
    status: 'Active',
    code_imobzi: 'BCD123',
    start_at: new Date('2023-07-10'),
    duration: 24,
    id_property_imobzi: inMemoryPropertiesRepositoryMock[1].id_imobzi,
    id_tenant_person_imobzi: null,
    id_tenant_organization_imobzi: null,
    id_main_guarantor_imobzi: inMemoryOrganizationsRepositoryMock[2].id_imobzi,
    fee: 950,
    guarantee_type: 'Bank Guarantee',
    guarantee_value: 1900,
    id_annual_readjustment_imobzi: 'ADJUSTMENT7',
    irrf: true,
    include_in_dimob: false,
    indeterminate: false,
    lease_value: 1200,
    beneficiaries: [],
    lease_items: [],
  },
  {
    id: 8,
    id_imobzi: 'YZA234',
    status: 'Active',
    code_imobzi: 'EFG789',
    start_at: new Date('2023-08-05'),
    duration: 36,
    id_property_imobzi: inMemoryPropertiesRepositoryMock[4].id_imobzi,
    id_tenant_person_imobzi: inMemoryPeopleRepositoryMock[4].id_imobzi,
    id_tenant_organization_imobzi: null,
    id_main_guarantor_imobzi: inMemoryPeopleRepositoryMock[1].id_imobzi,
    fee: 1200,
    guarantee_type: 'Security Deposit',
    guarantee_value: 2400,
    id_annual_readjustment_imobzi: 'ADJUSTMENT8',
    irrf: false,
    include_in_dimob: true,
    indeterminate: true,
    lease_value: 1700,
    beneficiaries: [],
    lease_items: [],
  },
];
