import { AnImobziInvoiceDTO } from 'src/3party-client/imobzi/imobzi-invoices/dto/an-imobzi-invoice.dtos';

export class ImobziInvoicesMock {
  pagination = {
    page1: {
      next_page: 2,
      invoices: [],
    },
    page2: {
      next_page: null,
      invoices: [],
    },
  };

  async getFullData(idInvoice: string): Promise<AnImobziInvoiceDTO> {
    return this.invoicesFullData.find((invoice) => invoice.invoice_id === idInvoice);
  }

  invoicesFullData = [
    {
      lease: {
        status: 'Active',
        db_id: 123,
        code: 'ABC-123',
      },
      invoice_url: 'https://example.com/invoice',
      subcategory: 'Rental',
      payment_method: 'Credit Card',
      send_overdue_notification: true,
      paid_at: '2023-11-03',
      payment_authentication: null,
      category: 'Housing',
      interest_value: 10.5,
      reference_start_at: '2023-10-01',
      bank_slip_url: 'https://example.com/bank-slip',
      payment_methods_available: 'Credit Card, Bank Transfer',
      bank_slip_id: 'XYZ-789',
      difference_value: 2.5,
      status: 'Paid',
      due_date: '2023-11-10',
      total_value: 1000.0,
      barcode: '1234567890',
      onlendings_and_fees: {
        managed_expenses_value: 50.0,
        first_management_fee_value: 100.0,
        management_fee_value: 50.0,
        predicted_onlendings: [],
        onlending_value: 0.0,
        predicted_onlending_value: 0.0,
        onlendings: [],
      },
      property: {
        code: 'PROP-001',
        city: 'Example City',
        state: 'Example State',
        db_id: 456,
        neighborhood: 'Example Neighborhood',
        address_complement: 'Apt 123',
        address: '123 Main Street',
        owners: [
          {
            db_id: 789,
            name: 'John Doe',
          },
          {
            db_id: 987,
            name: 'Jane Smith',
          },
        ],
        cover_photo: {
          url: 'https://example.com/cover-photo',
          db_id: 654,
        },
        zipcode: '12345-678',
      },
      invoice_paid_manual: null,
      account: {
        db_id: 345,
        name: 'Example Account',
      },
      charge_fee_value: 20.0,
      invoice_id: 'INV-456',
      created_at: '2023-10-25',
      value: 1000.0,
      bank_type: null,
      contact: {
        db_id: 123,
        type: 'Tenant',
        name: 'John Tenant',
        profile_image_url: null,
      },
      items: [
        {
          until_due_date: true,
          item_type: 'Rent',
          contact: null,
          invoice_item_id: 'ITEM-001',
          description: 'Monthly Rent Payment',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: false,
          value: 800.0,
          due_date: '2023-11-10',
        },
        {
          until_due_date: true,
          item_type: 'Management Fee',
          contact: null,
          invoice_item_id: 'ITEM-002',
          description: 'Monthly Management Fee',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: true,
          value: 100.0,
          due_date: '2023-11-10',
        },
        {
          until_due_date: true,
          item_type: 'Other Fee',
          contact: null,
          invoice_item_id: 'ITEM-003',
          description: 'Additional Fee',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: false,
          value: 100.0,
          due_date: '2023-11-10',
        },
      ],
      onlending_split: false,
      reference_end_at: '2023-11-30',
      created_manually: null,
      history: [
        {
          created_at: '2023-11-01',
          history_type: 'Payment',
          description: 'Payment received for invoice INV-456',
        },
        {
          created_at: '2023-10-28',
          history_type: 'Created',
          description: 'Invoice INV-456 created manually',
        },
      ],
    },
    {
      lease: {
        status: 'Inactive',
        db_id: 456,
        code: 'XYZ-789',
      },
      invoice_url: 'https://anotherexample.com/invoice',
      subcategory: 'Maintenance',
      payment_method: 'Bank Transfer',
      send_overdue_notification: false,
      paid_at: '2023-11-15',
      payment_authentication: null,
      category: 'Property Maintenance',
      interest_value: 5.0,
      reference_start_at: '2023-11-01',
      bank_slip_url: 'https://anotherexample.com/bank-slip',
      payment_methods_available: 'Bank Transfer',
      bank_slip_id: 'ABC-123',
      difference_value: 1.5,
      status: 'Pending',
      due_date: '2023-11-20',
      total_value: 750.0,
      barcode: '9876543210',
      onlendings_and_fees: {
        managed_expenses_value: 75.0,
        first_management_fee_value: 50.0,
        management_fee_value: 25.0,
        predicted_onlendings: [],
        onlending_value: 0.0,
        predicted_onlending_value: 0.0,
        onlendings: [],
      },
      property: {
        code: 'PROP-002',
        city: 'Another City',
        state: 'Another State',
        db_id: 789,
        neighborhood: 'Another Neighborhood',
        address_complement: 'Unit 456',
        address: '456 Elm Street',
        owners: [
          {
            db_id: 654,
            name: 'Alice Johnson',
          },
          {
            db_id: 987,
            name: 'Bob Smith',
          },
        ],
        cover_photo: {
          url: 'https://anotherexample.com/cover-photo',
          db_id: 321,
        },
        zipcode: '54321-876',
      },
      invoice_paid_manual: null,
      account: {
        db_id: 987,
        name: 'Another Account',
      },
      charge_fee_value: 15.0,
      invoice_id: 'INV-789',
      created_at: '2023-11-05',
      value: 750.0,
      bank_type: null,
      contact: {
        db_id: 456,
        type: 'Tenant',
        name: 'Alice Tenant',
        profile_image_url: null,
      },
      items: [
        {
          until_due_date: true,
          item_type: 'Maintenance',
          contact: null,
          invoice_item_id: 'ITEM-004',
          description: 'Monthly Maintenance Payment',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: false,
          value: 500.0,
          due_date: '2023-11-20',
        },
        {
          until_due_date: true,
          item_type: 'Management Fee',
          contact: null,
          invoice_item_id: 'ITEM-005',
          description: 'Monthly Management Fee',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: true,
          value: 50.0,
          due_date: '2023-11-20',
        },
        {
          until_due_date: true,
          item_type: 'Other Fee',
          contact: null,
          invoice_item_id: 'ITEM-006',
          description: 'Additional Fee',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: false,
          value: 200.0,
          due_date: '2023-11-20',
        },
      ],
      onlending_split: true,
      reference_end_at: '2023-11-30',
      created_manually: null,
      history: [
        {
          created_at: '2023-11-10',
          history_type: 'Payment',
          description: 'Payment received for invoice INV-789',
        },
        {
          created_at: '2023-11-05',
          history_type: 'Created',
          description: 'Invoice INV-789 created manually',
        },
      ],
    },
    {
      lease: {
        status: 'Active',
        db_id: 789,
        code: 'LMN-456',
      },
      invoice_url: 'https://yetanotherexample.com/invoice',
      subcategory: 'Utilities',
      payment_method: 'Direct Debit',
      send_overdue_notification: true,
      paid_at: '2023-11-08',
      payment_authentication: null,
      category: 'Utility Bills',
      interest_value: 3.5,
      reference_start_at: '2023-10-15',
      bank_slip_url: 'https://yetanotherexample.com/bank-slip',
      payment_methods_available: 'Direct Debit',
      bank_slip_id: 'DEF-789',
      difference_value: 1.0,
      status: 'Paid',
      due_date: '2023-11-15',
      total_value: 250.0,
      barcode: '5555555555',
      onlendings_and_fees: {
        managed_expenses_value: 30.0,
        first_management_fee_value: 20.0,
        management_fee_value: 10.0,
        predicted_onlendings: [],
        onlending_value: 0.0,
        predicted_onlending_value: 0.0,
        onlendings: [],
      },
      property: {
        code: 'PROP-003',
        city: 'Yet Another City',
        state: 'Yet Another State',
        db_id: 987,
        neighborhood: 'Another Neighborhood',
        address_complement: 'Unit 789',
        address: '789 Oak Street',
        owners: [
          {
            db_id: 123,
            name: 'Eva Wilson',
          },
          {
            db_id: 456,
            name: 'Charlie Brown',
          },
        ],
        cover_photo: {
          url: 'https://yetanotherexample.com/cover-photo',
          db_id: 555,
        },
        zipcode: '98765-4321',
      },
      invoice_paid_manual: null,
      account: {
        db_id: 654,
        name: 'Yet Another Account',
      },
      charge_fee_value: 7.5,
      invoice_id: 'INV-123',
      created_at: '2023-10-30',
      value: 250.0,
      bank_type: null,
      contact: {
        db_id: 789,
        type: 'Tenant',
        name: 'Eva Tenant',
        profile_image_url: null,
      },
      items: [
        {
          until_due_date: true,
          item_type: 'Utilities',
          contact: null,
          invoice_item_id: 'ITEM-007',
          description: 'Monthly Utility Payment',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: false,
          value: 180.0,
          due_date: '2023-11-15',
        },
        {
          until_due_date: true,
          item_type: 'Management Fee',
          contact: null,
          invoice_item_id: 'ITEM-008',
          description: 'Monthly Management Fee',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: true,
          value: 30.0,
          due_date: '2023-11-15',
        },
        {
          until_due_date: true,
          item_type: 'Other Fee',
          contact: null,
          invoice_item_id: 'ITEM-009',
          description: 'Additional Fee',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: false,
          value: 40.0,
          due_date: '2023-11-15',
        },
      ],
      onlending_split: true,
      reference_end_at: '2023-11-30',
      created_manually: null,
      history: [
        {
          created_at: '2023-11-08',
          history_type: 'Payment',
          description: 'Payment received for invoice INV-123',
        },
        {
          created_at: '2023-10-30',
          history_type: 'Created',
          description: 'Invoice INV-123 created manually',
        },
      ],
    },
    {
      lease: {
        status: 'Active',
        db_id: 101,
        code: 'XYZ-123',
      },
      invoice_url: 'https://onemoreexample.com/invoice',
      subcategory: 'Maintenance',
      payment_method: 'PayPal',
      send_overdue_notification: false,
      paid_at: '2023-11-17',
      payment_authentication: null,
      category: 'Property Maintenance',
      interest_value: 4.0,
      reference_start_at: '2023-10-20',
      bank_slip_url: 'https://onemoreexample.com/bank-slip',
      payment_methods_available: 'PayPal, Credit Card',
      bank_slip_id: 'PQR-456',
      difference_value: 2.0,
      status: 'Pending',
      due_date: '2023-11-25',
      total_value: 450.0,
      barcode: '7777777777',
      onlendings_and_fees: {
        managed_expenses_value: 40.0,
        first_management_fee_value: 30.0,
        management_fee_value: 10.0,
        predicted_onlendings: [],
        onlending_value: 0.0,
        predicted_onlending_value: 0.0,
        onlendings: [],
      },
      property: {
        code: 'PROP-004',
        city: 'One More City',
        state: 'One More State',
        db_id: 102,
        neighborhood: 'New Neighborhood',
        address_complement: 'Unit 101',
        address: '101 Pine Street',
        owners: [
          {
            db_id: 201,
            name: 'Grace Adams',
          },
          {
            db_id: 202,
            name: 'Daniel Miller',
          },
        ],
        cover_photo: {
          url: 'https://onemoreexample.com/cover-photo',
          db_id: 103,
        },
        zipcode: '12345-6789',
      },
      invoice_paid_manual: null,
      account: {
        db_id: 104,
        name: 'One More Account',
      },
      charge_fee_value: 6.0,
      invoice_id: 'INV-456',
      created_at: '2023-10-27',
      value: 450.0,
      bank_type: null,
      contact: {
        db_id: 203,
        type: 'Tenant',
        name: 'Grace Tenant',
        profile_image_url: null,
      },
      items: [
        {
          until_due_date: true,
          item_type: 'Maintenance',
          contact: null,
          invoice_item_id: 'ITEM-010',
          description: 'Monthly Maintenance Payment',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: false,
          value: 300.0,
          due_date: '2023-11-25',
        },
        {
          until_due_date: true,
          item_type: 'Management Fee',
          contact: null,
          invoice_item_id: 'ITEM-011',
          description: 'Monthly Management Fee',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: true,
          value: 30.0,
          due_date: '2023-11-25',
        },
        {
          until_due_date: true,
          item_type: 'Other Fee',
          contact: null,
          invoice_item_id: 'ITEM-012',
          description: 'Additional Fee',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: false,
          value: 60.0,
          due_date: '2023-11-25',
        },
      ],
      onlending_split: true,
      reference_end_at: '2023-11-30',
      created_manually: null,
      history: [
        {
          created_at: '2023-11-15',
          history_type: 'Payment',
          description: 'Payment received for invoice INV-456',
        },
        {
          created_at: '2023-10-27',
          history_type: 'Created',
          description: 'Invoice INV-456 created manually',
        },
      ],
    },
    {
      lease: {
        status: 'Inactive',
        db_id: 303,
        code: 'LMN-789',
      },
      invoice_url: 'https://onemoreexample.com/invoice',
      subcategory: 'Insurance',
      payment_method: 'Cash',
      send_overdue_notification: true,
      paid_at: '2023-11-20',
      payment_authentication: null,
      category: 'Insurance Premium',
      interest_value: 7.0,
      reference_start_at: '2023-10-10',
      bank_slip_url: 'https://onemoreexample.com/bank-slip',
      payment_methods_available: 'Cash, Check',
      bank_slip_id: 'JKL-101',
      difference_value: 3.0,
      status: 'Pending',
      due_date: '2023-11-30',
      total_value: 600.0,
      barcode: '9999999999',
      onlendings_and_fees: {
        managed_expenses_value: 50.0,
        first_management_fee_value: 40.0,
        management_fee_value: 10.0,
        predicted_onlendings: [],
        onlending_value: 0.0,
        predicted_onlending_value: 0.0,
        onlendings: [],
      },
      property: {
        code: 'PROP-005',
        city: 'Yet Another City',
        state: 'Yet Another State',
        db_id: 404,
        neighborhood: 'Newer Neighborhood',
        address_complement: 'Unit 202',
        address: '202 Maple Street',
        owners: [
          {
            db_id: 303,
            name: 'Oliver Turner',
          },
          {
            db_id: 505,
            name: 'Sophia Martinez',
          },
        ],
        cover_photo: {
          url: 'https://onemoreexample.com/cover-photo',
          db_id: 606,
        },
        zipcode: '54321-9876',
      },
      invoice_paid_manual: null,
      account: {
        db_id: 707,
        name: 'Premium Account',
      },
      charge_fee_value: 9.0,
      invoice_id: 'INV-789',
      created_at: '2023-10-15',
      value: 600.0,
      bank_type: null,
      contact: {},
      items: [
        {
          until_due_date: true,
          item_type: 'Insurance Premium',
          contact: null,
          invoice_item_id: 'ITEM-013',
          description: 'Monthly Insurance Premium',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: false,
          value: 500.0,
          due_date: '2023-11-30',
        },
        {
          until_due_date: true,
          item_type: 'Management Fee',
          contact: null,
          invoice_item_id: 'ITEM-014',
          description: 'Monthly Management Fee',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: true,
          value: 40.0,
          due_date: '2023-11-30',
        },
        {
          until_due_date: true,
          item_type: 'Other Fee',
          contact: null,
          invoice_item_id: 'ITEM-015',
          description: 'Additional Fee',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: false,
          value: 60.0,
          due_date: '2023-11-30',
        },
      ],
      onlending_split: true,
      reference_end_at: '2023-11-30',
      created_manually: null,
      history: [
        {
          created_at: '2023-11-20',
          history_type: 'Payment',
          description: 'Payment received for invoice INV-789',
        },
        {
          created_at: '2023-10-15',
          history_type: 'Created',
          description: 'Invoice INV-789 created manually',
        },
      ],
    },
    {
      lease: {
        status: 'Active',
        db_id: 202,
        code: 'ABC-789',
      },
      invoice_url: 'https://yetonemoreexample.com/invoice',
      subcategory: 'Maintenance',
      payment_method: 'Check',
      send_overdue_notification: true,
      paid_at: '2023-11-18',
      payment_authentication: null,
      category: 'Property Maintenance',
      interest_value: 6.0,
      reference_start_at: '2023-10-12',
      bank_slip_url: 'https://yetonemoreexample.com/bank-slip',
      payment_methods_available: 'Check, Bank Transfer',
      bank_slip_id: 'GHI-303',
      difference_value: 2.5,
      status: 'Pending',
      due_date: '2023-11-28',
      total_value: 550.0,
      barcode: '8888888888',
      onlendings_and_fees: {
        managed_expenses_value: 45.0,
        first_management_fee_value: 35.0,
        management_fee_value: 10.0,
        predicted_onlendings: [],
        onlending_value: 0.0,
        predicted_onlending_value: 0.0,
        onlendings: [],
      },
      property: {
        code: 'PROP-006',
        city: 'Yet One More City',
        state: 'Yet One More State',
        db_id: 505,
        neighborhood: 'Newest Neighborhood',
        address_complement: 'Unit 303',
        address: '303 Oak Street',
        owners: [
          {
            db_id: 404,
            name: 'Liam Hall',
          },
          {
            db_id: 707,
            name: 'Emma Davis',
          },
        ],
        cover_photo: {
          url: 'https://yetonemoreexample.com/cover-photo',
          db_id: 808,
        },
        zipcode: '65432-1098',
      },
      invoice_paid_manual: null,
      account: {
        db_id: 909,
        name: 'Yet One More Account',
      },
      charge_fee_value: 8.0,
      invoice_id: 'INV-101',
      created_at: '2023-10-18',
      value: 550.0,
      bank_type: null,
      contact: {
        db_id: 606,
        type: 'Tenant',
        name: 'Liam Tenant',
        profile_image_url: null,
      },
      items: [
        {
          until_due_date: true,
          item_type: 'Maintenance',
          contact: null,
          invoice_item_id: 'ITEM-016',
          description: 'Monthly Maintenance Payment',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: false,
          value: 400.0,
          due_date: '2023-11-28',
        },
        {
          until_due_date: true,
          item_type: 'Management Fee',
          contact: null,
          invoice_item_id: 'ITEM-017',
          description: 'Monthly Management Fee',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: true,
          value: 40.0,
          due_date: '2023-11-28',
        },
        {
          until_due_date: true,
          item_type: 'Other Fee',
          contact: null,
          invoice_item_id: 'ITEM-018',
          description: 'Additional Fee',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: false,
          value: 110.0,
          due_date: '2023-11-28',
        },
      ],
      onlending_split: true,
      reference_end_at: '2023-11-30',
      created_manually: null,
      history: [
        {
          created_at: '2023-11-18',
          history_type: 'Payment',
          description: 'Payment received for invoice INV-101',
        },
        {
          created_at: '2023-10-18',
          history_type: 'Created',
          description: 'Invoice INV-101 created manually',
        },
      ],
    },
    {
      lease: {
        status: 'Active',
        db_id: 303,
        code: 'XYZ-456',
      },
      invoice_url: 'https://yetanotherexample.com/invoice',
      subcategory: 'Security Deposit',
      payment_method: 'PayPal',
      send_overdue_notification: true,
      paid_at: '2023-11-22',
      payment_authentication: null,
      category: 'Deposit Payment',
      interest_value: 3.0,
      reference_start_at: '2023-10-18',
      bank_slip_url: 'https://yetanotherexample.com/bank-slip',
      payment_methods_available: 'PayPal, Credit Card',
      bank_slip_id: 'DEF-303',
      difference_value: 1.0,
      status: 'Pending',
      due_date: '2023-11-29',
      total_value: 300.0,
      barcode: '6666666666',
      onlendings_and_fees: {
        managed_expenses_value: 25.0,
        first_management_fee_value: 20.0,
        management_fee_value: 5.0,
        predicted_onlendings: [],
        onlending_value: 0.0,
        predicted_onlending_value: 0.0,
        onlendings: [],
      },
      property: {
        code: 'PROP-007',
        city: 'Yet Another City',
        state: 'Yet Another State',
        db_id: 404,
        neighborhood: 'Newer Neighborhood',
        address_complement: 'Unit 202',
        address: '202 Maple Street',
        owners: [
          {
            db_id: 303,
            name: 'Oliver Turner',
          },
          {
            db_id: 505,
            name: 'Sophia Martinez',
          },
        ],
        cover_photo: {
          url: 'https://yetanotherexample.com/cover-photo',
          db_id: 606,
        },
        zipcode: '54321-1098',
      },
      invoice_paid_manual: null,
      account: {
        db_id: 707,
        name: 'Deposit Account',
      },
      charge_fee_value: 6.0,
      invoice_id: 'INV-303',
      created_at: '2023-10-22',
      value: 300.0,
      bank_type: null,
      contact: {
        db_id: 606,
        type: 'Tenant',
        name: 'Sophia Tenant',
        profile_image_url: null,
      },
      items: [
        {
          until_due_date: true,
          item_type: 'Security Deposit',
          contact: null,
          invoice_item_id: 'ITEM-019',
          description: 'Monthly Deposit Payment',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: false,
          value: 250.0,
          due_date: '2023-11-29',
        },
        {
          until_due_date: true,
          item_type: 'Management Fee',
          contact: null,
          invoice_item_id: 'ITEM-020',
          description: 'Monthly Management Fee',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: true,
          value: 25.0,
          due_date: '2023-11-29',
        },
        {
          until_due_date: true,
          item_type: 'Other Fee',
          contact: null,
          invoice_item_id: 'ITEM-021',
          description: 'Additional Fee',
          behavior: 'Standard',
          landlords: [],
          include_in_dimob: true,
          charge_management_fee: false,
          value: 25.0,
          due_date: '2023-11-29',
        },
      ],
      onlending_split: true,
      reference_end_at: '2023-11-30',
      created_manually: null,
      history: [
        {
          created_at: '2023-11-22',
          history_type: 'Payment',
          description: 'Payment received for invoice INV-303',
        },
        {
          created_at: '2023-10-22',
          history_type: 'Created',
          description: 'Invoice INV-303 created manually',
        },
      ],
    },
  ];
}
