export const categoriesMocks = [
  {
    id: 1843888,
    descricao: 'Caução',
    cor: '#36e55a',
    wgi_usuario_id: 99784,
    ativo: true,
    tipo_categoria_id: 0,
    categorias_filhas: [
      {
        id: 1843889,
        descricao: 'Caução Recebido',
        cor: '#36e55a',
        parent_id: 1843888,
        ativo: true,
        tipo_categoria_id: 0,
        categorias_filhas: [],
      },
      {
        id: 1843890,
        descricao: 'Caução Devolvido',
        cor: '#36e55a',
        parent_id: 1843888,
        ativo: true,
        tipo_categoria_id: 0,
        categorias_filhas: [],
      },
    ],
  },
  {
    id: 1851253,
    descricao: 'Cobrança Imobzi',
    cor: '#009900',
    wgi_usuario_id: 99786,
    ativo: true,
    tipo_categoria_id: 0,
    categorias_filhas: [],
  },
  {
    id: 1837236,
    descricao: 'Custos com funcionários',
    cor: '#E4FF00',
    wgi_usuario_id: 99784,
    ativo: true,
    tipo_categoria_id: 1,
    categorias_filhas: [
      {
        id: 1837237,
        descricao: '13º Salário',
        cor: '#D0E800',
        parent_id: 1837236,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
      {
        id: 1837238,
        descricao: 'Férias',
        cor: '#BCD200',
        parent_id: 1837236,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
      {
        id: 1837239,
        descricao: 'FGTS',
        cor: '#B2C700',
        parent_id: 1837236,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
      {
        id: 1837240,
        descricao: 'INSS',
        cor: '#9EB100',
        parent_id: 1837236,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
      {
        id: 1837241,
        descricao: 'Outros custos com funcionários',
        cor: '#8C9C00',
        parent_id: 1837236,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
      {
        id: 1837242,
        descricao: 'Salários',
        cor: '#768400',
        parent_id: 1837236,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
    ],
  },
  {
    id: 1837232,
    descricao: 'Custos com sócios',
    cor: '#FBE700',
    wgi_usuario_id: 99784,
    ativo: true,
    tipo_categoria_id: 1,
    categorias_filhas: [
      {
        id: 1837234,
        descricao: 'Outros custos com sócios',
        cor: '#DAC900',
        parent_id: 1837232,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
      {
        id: 1837235,
        descricao: 'Pró-labore',
        cor: '#C5B600',
        parent_id: 1837232,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
    ],
  },
  {
    id: 1837265,
    descricao: 'Despesas financeiras',
    cor: '#e73500',
    wgi_usuario_id: 99784,
    ativo: true,
    tipo_categoria_id: 1,
    categorias_filhas: [
      {
        id: 1837266,
        descricao: 'Imposto sobre aplicações',
        cor: '#dc3200',
        parent_id: 1837265,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
      {
        id: 1837267,
        descricao: 'Outras despesas operacionais',
        cor: '#ce2f00',
        parent_id: 1837265,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
      {
        id: 1837268,
        descricao: 'Taxas e tarifas bancárias',
        cor: '#b72a00',
        parent_id: 1837265,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
    ],
  },
  {
    id: 1837258,
    descricao: 'Despesas operacionais',
    cor: '#E70000',
    wgi_usuario_id: 99784,
    ativo: true,
    tipo_categoria_id: 1,
    categorias_filhas: [
      {
        id: 1837259,
        descricao: 'Assinaturas',
        cor: '#C70000',
        parent_id: 1837258,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
      {
        id: 1837260,
        descricao: 'Escritório',
        cor: '#B60000',
        parent_id: 1837258,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
      {
        id: 1837261,
        descricao: 'Despesas com prestação de serviços',
        cor: '#9B0000',
        parent_id: 1837258,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
      {
        id: 1837262,
        descricao: 'Despesas tributárias',
        cor: '#860000',
        parent_id: 1837258,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
      {
        id: 1837263,
        descricao: 'Outras despesas operacionais',
        cor: '#730000',
        parent_id: 1837258,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
      {
        id: 1843956,
        descricao: 'Taxa de Boleto',
        cor: '#e051ff',
        parent_id: 1837258,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
      {
        id: 1843959,
        descricao: 'Taxa de Cartão',
        cor: '#E70000',
        parent_id: 1837258,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
    ],
  },
  {
    id: 1837273,
    descricao: 'Distribuição de Lucros ou Dividendos',
    cor: '#6469f7',
    wgi_usuario_id: 99784,
    ativo: true,
    tipo_categoria_id: 1,
    categorias_filhas: [
      {
        id: 1837274,
        descricao: 'Distribuição de Lucros',
        cor: '#494ff7',
        parent_id: 1837273,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
      {
        id: 1837275,
        descricao: 'Dividendos',
        cor: '#2c33f9',
        parent_id: 1837273,
        ativo: true,
        tipo_categoria_id: 1,
        categorias_filhas: [],
      },
    ],
  },
  {
    id: 1837269,
    descricao: 'Outras receitas',
    cor: '#49d600',
    wgi_usuario_id: 99784,
    ativo: true,
    tipo_categoria_id: 2,
    categorias_filhas: [],
  },
  {
    id: 1837246,
    descricao: 'Outros custos fixos',
    cor: '#6c01af',
    wgi_usuario_id: 99784,
    ativo: true,
    tipo_categoria_id: 1,
    categorias_filhas: [],
  },
  {
    id: 1837911,
    descricao: 'Recebimentos por Boleto',
    cor: '#d40eff',
    wgi_usuario_id: 99784,
    ativo: true,
    tipo_categoria_id: 0,
    categorias_filhas: [
      {
        id: 1837912,
        descricao: 'Condomínio',
        cor: '#EE0000',
        parent_id: 1837911,
        ativo: true,
        tipo_categoria_id: 0,
        categorias_filhas: [],
      },
      {
        id: 1843892,
        descricao: 'IPTU',
        cor: '#e051ff',
        parent_id: 1837911,
        ativo: true,
        tipo_categoria_id: 0,
        categorias_filhas: [],
      },
      {
        id: 1843893,
        descricao: 'Manutenção',
        cor: '#ffaea5',
        parent_id: 1837911,
        ativo: true,
        tipo_categoria_id: 0,
        categorias_filhas: [],
      },
      {
        id: 1843894,
        descricao: 'Honorários Advocatícios',
        cor: '#999999',
        parent_id: 1837911,
        ativo: true,
        tipo_categoria_id: 0,
        categorias_filhas: [],
      },
      {
        id: 1843895,
        descricao: 'Multa Contratual',
        cor: '#aed2ff',
        parent_id: 1837911,
        ativo: true,
        tipo_categoria_id: 0,
        categorias_filhas: [],
      },
      {
        id: 1846027,
        descricao: 'Aluguel',
        cor: '#114477',
        parent_id: 1837911,
        ativo: true,
        tipo_categoria_id: 0,
        categorias_filhas: [],
      },
      {
        id: 1846090,
        descricao: 'I.R.R.F.',
        cor: '#d40eff',
        parent_id: 1837911,
        ativo: true,
        tipo_categoria_id: 0,
        categorias_filhas: [],
      },
      {
        id: 1846091,
        descricao: 'Desconto/Bonificação ao Locatário',
        cor: '#ff4e3b',
        parent_id: 1837911,
        ativo: true,
        tipo_categoria_id: 0,
        categorias_filhas: [],
      },
      {
        id: 1848070,
        descricao: 'Juros e Multa de Faturas',
        cor: '#d40eff',
        parent_id: 1837911,
        ativo: true,
        tipo_categoria_id: 0,
        categorias_filhas: [],
      },
      {
        id: 1891062,
        descricao: 'Taxa de Assinatura',
        cor: '#d40eff',
        parent_id: 1837911,
        ativo: true,
        tipo_categoria_id: 0,
        categorias_filhas: [],
      },
      {
        id: 1891063,
        descricao: 'Seguro Incêndio',
        cor: '#d40eff',
        parent_id: 1837911,
        ativo: true,
        tipo_categoria_id: 0,
        categorias_filhas: [],
      },
    ],
  },
  {
    id: 1837219,
    descricao: 'Receitas de Comissões',
    cor: '#009900',
    wgi_usuario_id: 99784,
    ativo: true,
    tipo_categoria_id: 2,
    categorias_filhas: [
      {
        id: 1837220,
        descricao: 'Comissão de Venda',
        cor: '#007700',
        parent_id: 1837219,
        ativo: true,
        tipo_categoria_id: 2,
        categorias_filhas: [],
      },
      {
        id: 1837221,
        descricao: 'Comissão de Aluguel',
        cor: '#005700',
        parent_id: 1837219,
        ativo: true,
        tipo_categoria_id: 2,
        categorias_filhas: [],
      },
    ],
  },
  {
    id: 1837264,
    descricao: 'Rendimento de investimentos',
    cor: '#4fe402',
    wgi_usuario_id: 99784,
    ativo: true,
    tipo_categoria_id: 2,
    categorias_filhas: [],
  },
  {
    id: 1838279,
    descricao: 'Sem categoria',
    cor: '#CC3366',
    wgi_usuario_id: 99784,
    ativo: true,
    tipo_categoria_id: 0,
    categorias_filhas: [],
  },
  {
    id: 1860961,
    descricao: 'Transferência de comissão entre contas',
    cor: '#d40eff',
    wgi_usuario_id: 99784,
    ativo: true,
    tipo_categoria_id: 0,
    categorias_filhas: [],
  },
];
