export const categoriesMocks = {
  id: 1837911,
  descricao: 'Recebimentos por Boleto',
  cor: '#d40eff',
  wgi_usuario_id: 99784,
  ativo: true,
  tipo_categoria_id: 0,
  categorias_filhas: [
    {
      id: 1837912,
      descricao: 'Condomínio',
      cor: '#EE0000',
      parent_id: 1837911,
      ativo: true,
      tipo_categoria_id: 0,
      categorias_filhas: [],
    },
    {
      id: 1843892,
      descricao: 'IPTU',
      cor: '#e051ff',
      parent_id: 1837911,
      ativo: true,
      tipo_categoria_id: 0,
      categorias_filhas: [],
    },
    {
      id: 1843893,
      descricao: 'Manutenção',
      cor: '#ffaea5',
      parent_id: 1837911,
      ativo: true,
      tipo_categoria_id: 0,
      categorias_filhas: [],
    },
    {
      id: 1843894,
      descricao: 'Honorários Advocatícios',
      cor: '#999999',
      parent_id: 1837911,
      ativo: true,
      tipo_categoria_id: 0,
      categorias_filhas: [],
    },
    {
      id: 1843895,
      descricao: 'Multa Contratual',
      cor: '#aed2ff',
      parent_id: 1837911,
      ativo: true,
      tipo_categoria_id: 0,
      categorias_filhas: [],
    },
    {
      id: 1846027,
      descricao: 'Aluguel',
      cor: '#114477',
      parent_id: 1837911,
      ativo: true,
      tipo_categoria_id: 0,
      categorias_filhas: [],
    },
    {
      id: 1846090,
      descricao: 'I.R.R.F.',
      cor: '#d40eff',
      parent_id: 1837911,
      ativo: true,
      tipo_categoria_id: 0,
      categorias_filhas: [],
    },
    {
      id: 1846091,
      descricao: 'Desconto/Bonificação ao Locatário',
      cor: '#ff4e3b',
      parent_id: 1837911,
      ativo: true,
      tipo_categoria_id: 0,
      categorias_filhas: [],
    },
    {
      id: 1848070,
      descricao: 'Juros e Multa de Faturas',
      cor: '#d40eff',
      parent_id: 1837911,
      ativo: true,
      tipo_categoria_id: 0,
      categorias_filhas: [],
    },
    {
      id: 1891062,
      descricao: 'Taxa de Assinatura',
      cor: '#d40eff',
      parent_id: 1837911,
      ativo: true,
      tipo_categoria_id: 0,
      categorias_filhas: [],
    },
    {
      id: 1891063,
      descricao: 'Seguro Incêndio',
      cor: '#d40eff',
      parent_id: 1837911,
      ativo: true,
      tipo_categoria_id: 0,
      categorias_filhas: [],
    },
  ],
};
